### ISSUE TITLE
verifyCollection User-provided metadata must result in same user-provided data hash

### ISSUE THREAD

**Issue by solpower** [metaplex-foundation/mpl-bubblegum#119]
Verifying Collections error

---- 1. createCollectionNft

const collectionMint = generateSigner(umi)
console.log(collectionMint);

const tb = await createNft(umi, {
  mint: collectionMint,
  name: 'test rider Collection',
  uri: 'https://ipfs.*.net/test2/collection.json',
  sellerFeeBasisPoints: percentAmount(0), // 0%
  isCollection: true,
})
const resp = tb.sendAndConfirm(umi)

---- 2. mintNft

const merkleTreePub = publicKey("4vgZnafoPbmjpdGYGmfJTNUgoHBK7oQvtB2FXUGPB8H3");
const newOwner = publicKey('BMfsXsPkyVqnMy1BHS22oVT5ViikjXMbEhU4txc4DmhE');
const collectionPub = publicKey("7kNL9B6vb1PUZkrkh3jbJtfRFrVYGUQfzS2D7X5CRMWj");
const creatorPub = publicKey("AX4KgeC6Ti4G51arJHgJuq23cxQsTvvkGsEeXzEDzESs");

const tb = await mintV1(umi, {
  leafOwner: newOwner,
  merkleTree: merkleTreePub,
  metadata: {
    name: 'rider cNFT #2',
    uri: 'https://ipfs.*.net/test2/2.json',
    sellerFeeBasisPoints: 0, // 0%
    collection: { key: collectionPub, verified: false },
    creators: [
      { address: creatorPub, verified: true, share: 100 },
    ],
  },
})
.sendAndConfirm(umi, { send: { commitment: 'finalized' } })

---- 3. verifyCollection

const collectionPub = publicKey("7kNL9B6vb1PUZkrkh3jbJtfRFrVYGUQfzS2D7X5CRMWj");
const assetId = publicKey("DuTYBq8MH6G9UW3B5bdZCmZu2qGtrXFV5es1oJ6QuNXL");
const assetWithProof = await getAssetWithProof(umi, assetId)
console.log(assetWithProof);
const resp = await verifyCollection(umi, {
  ...assetWithProof,
  collectionMint: collectionPub,
  collectionAuthority: umi.identity,
}).sendAndConfirm(umi);

sent step 1, step 2 mintNft first, and then after about 5 minutes , I did step 3 verifyCollection.  get the error 

ERROR
User-provided metadata must result in same user-provided data hash

Source: Program > mplBubblegum [BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY]

Caused By: Error: Simulation failed. 
Message: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x177a. 
Logs: 
[
  "Program BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY invoke [1]",
  "Program log: Instruction: VerifyCollection",
  "Program log: AnchorError occurred. Error Code: DataHashMismatch. Error Number: 6010. Error Message: User-provided metadata must result in same user-provided data hash.",
  "Program BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY consumed 21391 of 200000 compute units",
  "Program BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY failed: custom program error: 0x177a"
]. 
Catch the `SendTransactionError` and call `getLogs()` on it for full details.

Program Logs:
| Program BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY invoke [1]
| Program log: Instruction: VerifyCollection
| Program log: AnchorError occurred. Error Code: DataHashMismatch. Error Number: 6010. Error Message: User-provided metadata must result in same user-provided data hash.
| Program BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY consumed 21391 of 200000 compute units
| Program BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY failed: custom program error: 0x177a

DataHashMismatch: User-provided metadata must result in same user-provided data hash
    at getMplBubblegumErrorFromCode (webpack-internal:///./node_modules/@metaplex-foundation/mpl-bubblegum/dist/src/generated/errors/mplBubblegum.js:482:26)
    at Object.getErrorFromCode (webpack-internal:///./node_modules/@metaplex-foundation/mpl-bubblegum/dist/src/generated/programs/mplBubblegum.js:18:62)
    at Object.resolveError (webpack-internal:///./node_modules/@metaplex-foundation/umi-program-repository/dist/esm/createDefaultProgramRepository.mjs:89:35)
    at Object.sendTransaction (webpack-internal:///./node_modules/@metaplex-foundation/umi-rpc-web3js/dist/esm/createWeb3JsRpc.mjs:170:42)
    at async TransactionBuilder.sendAndConfirm (webpack-internal:///./node_modules/@metaplex-foundation/umi/dist/cjs/TransactionBuilder.cjs:213:23)
    at async verify (webpack-internal:///./node_modules/ts-loader/index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/components/HelloWorld.vue?vue&type=script&lang=ts:28:18)

getAssetProof  response:

helius getAssetProof  is the same with  the umi code  getAssetWithProof(umi, assetId)  ，

{
    "jsonrpc": "2.0",
    "result": {
        "root": "DUKanhfRAi6gg1c9mPhYJNpek8RH8SesQ3zgHoS1NuJZ",
        "proof": [
            "8JeR95YdYF1YbnjjT5NHhEPSCpvCq27wagro8R6REb1z",
            "HW9HFdXX1wQR9qg8yf6UQBTuRqyPDWkuTqqSjssCMnh9",
            "DAbAU9srHpEUogXWuhy5VZ7g8UX9STymELtndcx1xgP1",
            "3HCYqQRcQSChEuAw1ybNYHibrTNNjzbYzm56cmEmivB6",
            "GSz87YKd3YoZWcEKhnjSsYJwv8o5aWGdBdGGYUphRfTh",
            "DDKRiV9THMXkPj1X4gZmvYCe9c3w39gwAYwUeppCcziv",
            "ABnEXHmveD6iuMwfw2po7t6TPjn5kYMVwYJMi3fa9K91",
            "JDh7eiWiUWtiWn623iybHqjQ6AQ6c2Czz8m6ZxwSCkta",
            "BFvmeiEuzAYcMR8YxcuCMGYPDpjcmP5hsNbcswgQ8pMc",
            "EvxphsdRErrDMs9nhFfF4nzq8i1C2KSogA7uB96TPpPR",
            "HpMJWAzQv9HFgHBqY1o8V1B27sCYPFHJdGivDA658jEL",
            "HjnrJn5vBUUzpCxzjjM9ZnCPuXei2cXKJjX468B9yWD7",
            "4YCF1CSyTXm1Yi9W9JeYevawupkomdgy2dLxEBHL9euq"
        ],
        "node_index": 8225,
        "leaf": "6KWgzLC2wBTDPq1db73NdojSqUF2PE9uNPChbYKcpXHC",
        "tree_id": "4vgZnafoPbmjpdGYGmfJTNUgoHBK7oQvtB2FXUGPB8H3"
    },
    "id": "ec7f8ed8-d91e-4143-9b40-1edf931ede8d"
}

**Comment by danenbm** [comment]
Hey, thanks for the detailed report.

The issue is a bug in our `getAssetWithProof` helper — it hardcodes `collection.verified: true` when reconstructing the metadata, regardless of the actual on-chain state. Since you minted with `collection: { key: collectionPub, verified: false }`, the on-chain data hash was computed with `verified: false`. When `verifyCollection` re-hashes the metadata from `getAssetWithProof`, the `verified: true` produces a different hash, causing the `DataHashMismatch`.

We'll get a fix out for this in the SDK. In the meantime, you can work around it by overriding the collection field before passing it to `verifyCollection`:

```typescript
const assetWithProof = await getAssetWithProof(umi, assetId);

assetWithProof.metadata.collection = some({
  key: collectionPub,
  verified: false,
});

const resp = await verifyCollection(umi, {
  ...assetWithProof,
  collectionMint: collectionPub,
  collectionAuthority: umi.identity,
}).sendAndConfirm(umi);
```

You need to pass metadata matching the *current* (pre-verification) state so the data hash check passes. The `verifyCollection` instruction itself will flip `verified` to `true` on-chain.

**Comment by danenbm** [comment]
Addressed in https://github.com/metaplex-foundation/mpl-bubblegum/pull/164 will deploy soon
